<a href="https://colab.research.google.com/github/Jojohere05/PRODIGY_DS_02/blob/main/prodigy_task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
add='https://github.com/m4gaikwad/PandasTutorial/raw/main/online_store_customer_data.csv'

In [ ]:
df=pd.read_csv(add,on_bad_lines='skip')
df.head(10)

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
0,1/1/2019,151200,Female,19.0,Single,Kansas,Basic,Unemployment,Other,1.0,2051.36
1,1/1/2019,151201,Male,49.0,Single,Illinois,Basic,self-employed,Card,0.0,544.04
2,1/1/2019,151202,Male,63.0,Married,New Mexico,Basic,workers,PayPal,1.0,1572.60
3,1/1/2019,151203,NaN,18.0,Single,Virginia,Platinum,workers,Card,1.0,1199.79
4,1/1/2019,151204,Male,27.0,Single,Connecticut,Basic,self-employed,Card,0.0,NaN
5,1/3/2019,151205,Male,71.0,Single,Hawaii,Basic,Employees,PayPal,1.0,2922.66
6,1/3/2019,151206,Female,34.0,Married,New Mexico,Platinum,Employees,PayPal,1.0,1481.42
7,1/3/2019,151207,Male,37.0,Married,Connecticut,Basic,workers,PayPal,1.0,1149.55
8,1/4/2019,151208,Male,75.0,Married,Florida,Silver,Employees,Card,0.0,1046.20
9,1/4/2019,151209,Female,41.0,Married,Vermont,Gold,Unemployment,Card,1.0,2730.60

## **Cleaning of** **data**

In [ ]:
df.shape

(2512, 11)

In [48]:
df.Age.isna().sum()

0

In [52]:
df.isna().sum()

Transaction_date      0
Transaction_ID        0
Gender               28
Age                   0
Marital_status        0
State_names           0
Segment               0
Employees_status     26
Payment_method        0
Referal             155
Amount_spent        242
dtype: int64

In [ ]:
df.isna().sum().sum()

451

In [51]:
cleaned_dataset=df.dropna(subset=['Gender','Referal','Amount_spent'])
print(cleaned_dataset)

     Transaction_date  Transaction_ID  Gender   Age Marital_status  \
0            1/1/2019          151200  Female  19.0         Single
1            1/1/2019          151201    Male  49.0         Single
2            1/1/2019          151202    Male  63.0        Married
5            1/3/2019          151205    Male  71.0         Single
6            1/3/2019          151206  Female  34.0        Married
...               ...             ...     ...   ...            ...
2506        4/30/2021          153694    Male  34.0         Single
2507         5/1/2021          153695  Female  57.0         Single
2508         5/1/2021          153696  Female  36.0        Married
2509         5/1/2021          153697    Male  22.0         Single
2511         5/1/2021          153699    Male  48.0         Single

         State_names   Segment Employees_status Payment_method  Referal  \
0             Kansas     Basic     Unemployment          Other      1.0
1           Illinois     Basic    self-employed           Card      0.0
2         New Mexico     Basic          workers         PayPal      1.0
5             Hawaii     Basic        Employees         PayPal      1.0
6         New Mexico  Platinum        Employees         PayPal      1.0
...              ...       ...              ...            ...      ...
2506         Florida   Missing        Employees          Other      1.0
2507  South Carolina  Platinum    self-employed           Card      0.0
2508          Hawaii    Silver    self-employed         PayPal      1.0
2509  South Carolina     Basic          workers         PayPal      1.0
2511      California    Silver          workers         PayPal      1.0

      Amount_spent
0          2051.36
1           544.04
2          1572.60
5          2922.66
6          1481.42
...            ...
2506        286.82
2507        150.10
2508        708.88
2509       2030.07
2511       1073.15

[2104 rows x 11 columns]

# **Data Analysis**

In [56]:
df[(df['Age']<=40)&(df['Gender']=='Female')&(df['Marital_status']=='Single')]

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
0,1/1/2019,151200,Female,19.0,Single,Kansas,Basic,Unemployment,Other,1.0,2051.36
24,1/10/2019,151224,Female,32.0,Single,Montana,Basic,Employees,PayPal,0.0,2737.41
31,1/13/2019,151231,Female,21.0,Single,Montana,Basic,Employees,Card,0.0,2035.07
42,1/17/2019,151242,Female,16.0,Single,Texas,Gold,self-employed,PayPal,1.0,938.16
58,1/25/2019,151258,Female,32.0,Single,South Carolina,Basic,Employees,Other,NaN,676.70
...,...,...,...,...,...,...,...,...,...,...,...
2404,3/27/2021,153592,Female,39.0,Single,Utah,Silver,Employees,Other,1.0,2954.83
2420,4/2/2021,153608,Female,37.0,Single,Michigan,Basic,Employees,PayPal,0.0,807.37
2423,4/3/2021,153611,Female,27.0,Single,South Carolina,Silver,workers,Card,1.0,NaN
2459,4/14/2021,153647,Female,24.0,Single,Vermont,Basic,NaN,Card,1.0,830.59
2472,4/19/2021,153660,Female,16.0,Single,New Jersey,Basic,self-employed,PayPal,NaN,2027.31

In [57]:
import numpy as np

In [58]:
df['Age_category']=np.where(df['Age']<30,'Young',np.where(df['Age']<=50,'middle_aged','old'))

In [59]:
df['Age_category']

0             Young
1       middle_aged
2               old
3             Young
4             Young
           ...
2507            old
2508    middle_aged
2509          Young
2510    middle_aged
2511    middle_aged
Name: Age_category, Length: 2512, dtype: object

In [60]:
df.groupby(['Age_category'])['Age'].count()

Age_category
Young           537
middle_aged     902
old            1073
Name: Age, dtype: int64

In [63]:
df[['Age_category','Amount_spent']].groupby(df['Age_category']).mean()

<ipython-input-63-f7b2fdc7bed1>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df[['Age_category','Amount_spent']].groupby(df['Age_category']).mean()

              Amount_spent
Age_category
Young          1478.187584
middle_aged    1391.679877
old            1411.606673

In [64]:
pd.crosstab(df['Age_category'],df['Marital_status'])

Marital_status  Married  Single
Age_category
Young               321     216
middle_aged         527     375
old                 625     448